services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - "."
  worker:
    build:
      context: celery_queue
      dockerfile: Dockerfile
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes:
      - "./celery_queue:/queue"
  monitor:
    build:
      context: celery_queue
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    command: [ 'celery', '-A', 'tasks', 'worker' ]
    environment:
        CELERY_BROKER_URL: redis://redis:6379/0
        CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - worker
    volumes:
      - './celery_queue:/queue'
  redis:
    image: redis:latest
    ports:
        - "6379:6379"